#: import Factory kivy.factory.Factory

<FrostedGlassMV@ModalView>:
    size_hint: 0.85, 0.4
    frosted_glass_bg: None
    background_color: 0, 0, 0, 0
    FrostedGlass:
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        background: root.frosted_glass_bg
        blur_size: 30
        saturation: 1.2
        luminosity: 1.2
        overlay_color: "FFFFFF80"
        noise_opacity: 0.13
        border_radius:  dp(5), dp(50), dp(5), dp(50)
        outline_color: self.overlay_color
        outline_width: 0.5
        BoxLayout:
            size_hint: 0.8, 0.15
            pos_hint: {'center_x': 0.5,'y': 0.1}
            spacing: dp(20)
            Button:
                text: "cancel"
                on_release:
                    root.dismiss()
            Button:
                text: "ok"
                on_release:
                    root.dismiss()

<UI>:
    canvas:
        Color:
            rgba: rgba("#ffffff")
        Rectangle:
            size: self.size
            pos: self.pos
    ScreenManager:
        id: sm
        Screen1:
            name: 'screen_1'
        Screen2:
            name: 'screen_2'
        Screen3:
            name: 'screen_3'
        Screen4:
            name: 'screen_4'
    GridLayout:
        rows: 2
        cols: 2
        size_hint: (1, None)
        height: dp(90)
        pos_hint: {'top': 0.98}
        Button:
            text: 'static'
            on_release:
                root.ids.sm.current = 'screen_1'
        Button:
            text: 'moving\nbackground'
            on_release:
                root.ids.sm.current = 'screen_2'
        Button:
            text: 'moving\nFrostedGlass'
            on_release:
                root.ids.sm.current = 'screen_3'
        Button:
            text: 'inside\nModalView'
            on_release:
                root.ids.sm.current = 'screen_4'


# Example 1
<Screen1>:
    Image:
        id: background_image
        source: 'kivy_logo.png'
        size_hint: (1, 1)
        allow_stretch: True
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        canvas.before:
            Color:
                rgba: rgba("#FFB74D")
            Rectangle:
                size: self.size
                pos: self.pos

    FrostedGlass:
        background: background_image
        size_hint: (0.48, 0.48)
        pos_hint: {'top': 1}
        blur_size: 10
        saturation: 1.2
        luminosity: 1.3
        overlay_color: "#ffffffA6"
        noise_opacity: 0.1
        border_radius:  0, 0, dp(50), 0
        outline_color: "#000000"
        outline_width: 1

    FrostedGlass:
        background: background_image
        size_hint: (0.48, 0.48)
        pos_hint: {'right': 1,'top': 1}
        blur_size: 20
        saturation: 1.2
        luminosity: 1.4
        overlay_color: "#388E3CA6"
        noise_opacity: 0.1
        border_radius:  0, 0, 0, dp(50)
        outline_color: "#388E3C"
        outline_width: 1

    FrostedGlass:
        background: background_image
        size_hint: (0.48, 0.48)
        pos_hint: {'right': 1}
        blur_size: 30
        saturation: 1.2
        luminosity: 1.4
        overlay_color: "#D32F2FA6"
        noise_opacity: 0.1
        border_radius:  dp(50), 0, 0, 0
        outline_color: "#D32F2F"
        outline_width: 1

    FrostedGlass:
        background: background_image
        size_hint: (0.48, 0.48)
        blur_size: 40
        saturation: 1.2
        luminosity: 1.4
        overlay_color: "#1976D2A6"
        noise_opacity: 0.1
        border_radius:  0, dp(50), 0, 0
        outline_color: "#1976D2"
        outline_width: 1



# Example 2
<Screen2>:
    ScrollView:
        id: scroll_view
        canvas.before:
            Color:
                rgba: rgba("#0097A7")
            Rectangle:
                size: self.size
                pos: self.pos
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1, 2)
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}

    FrostedGlass:
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        background: scroll_view
        size_hint: (0.7, 0.35)
        blur_size: 25
        saturation: 1.2
        luminosity: 1.2
        overlay_color: "#F57C00A6"
        noise_opacity: 0.13
        border_radius:  dp(20), dp(20), dp(20), dp(20)
        outline_color: "#F57C00"
        outline_width: 0.5


# Example 3
<Screen3>:
    Image:
        id: background_image
        source: 'bg_example.png'
        size_hint: (1, 1)
        allow_stretch: True
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        canvas.before:
            Color:
                rgba: rgba("#FFB74D")
            Rectangle:
                size: self.size
                pos: self.pos

    ScrollView:
        id: scroll_view
        pos_hint: {'center_y': 0.5}
        size_hint: (1, 0.4)
        do_scroll_y: False

        BoxLayout:
            size_hint: (2, 1)
            spacing: dp(30)
            padding: dp(10)
            FrostedGlass:
                background: background_image
                size_hint: (0.4, 1)
                blur_size: 20
                saturation: 1.2
                luminosity: 1.5
                overlay_color: "#76FF03A6"
                noise_opacity: 0.1
                border_radius:  dp(10), dp(10), dp(10), dp(10)
                outline_color: "#76FF03"
                outline_width: 1
            FrostedGlass:
                background: background_image
                size_hint: (0.4, 1)
                blur_size: 35
                saturation: 1.2
                luminosity: 1.5
                overlay_color: "#FDD835A6"
                noise_opacity: 0.1
                border_radius:  dp(10), dp(10), dp(10), dp(10)
                outline_color: "#FDD835"
                outline_width: 1
            FrostedGlass:
                background: background_image
                size_hint: (0.4, 1)
                blur_size: 50
                saturation: 1.5
                luminosity: 1.5
                overlay_color: "#808080A6"
                noise_opacity: 0.1
                border_radius:  dp(10), dp(10), dp(10), dp(10)
                outline_color: "#000000"
                outline_width: 1


# Example 4
<Screen4>:
    id: screen_4
    ScrollView:
        id: scroll_view
        canvas.before:
            Color:
                rgba: rgba("#76FF03")
            Rectangle:
                size: self.size
                pos: self.pos
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1, 2)
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
            Image:
                source: 'kivy_logo.png'
                size_hint: (1, 1)
                allow_stretch: True
                pos_hint: {'center_x': 0.5,'center_y': 0.5}

    Button:
        text: "Open"
        size_hint: None, None
        size: dp(100), dp(40)
        pos_hint: {'center_x': 0.5,'center_y': 0.15}
        on_press:
            popup = Factory.FrostedGlassMV()
            popup.frosted_glass_bg = screen_4
            popup.open()
